#
#  YAML File to test the HEBI node
#
#  If you start the node via the launch file, you can specify the
#  parameters there.
#
#  If you start the node directly with 'ros2 run', you will need to
#  specify the pameters here and run:
#
#    ros2 run hebiros hebinode --ros-args --params-file <this_file_name>
#
hebinode:
  ros__parameters:
    testmode: 'off'
    family: 'robotlab'
    motors: ['4.3', '4.4', '4.5']
    joints: ['one', 'two', 'three']
    rate:   100.0
